[environments]
  [environments.development]
    name = "sns-elasticsearch"
    namespace = "elasticsearch"
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = false
    dockerfile = "Dockerfile"
    chart = ""
